app/models.py
import pandas as pd
from pymongo import MongoClient
import matplotlib.pyplot as plt
import seaborn as sns
from joblib import load
import matplotlib.pyplot as plt
import ssl
import pyautogui


def predict(dep,agg, atm, lum, date, cat_time, journee, vacances):    
    model = load('app/static/visa.joblib')
    secours = model.predict([[dep,agg, atm, lum, date, cat_time, journee, vacances]])
    return secours
	

app/__init__.py
# coding: utf8
# Depuis flask on importe la classe Flask qui représente l'application WSGI
# Une application WGI est, pour faire simple, un ensemble de comportement et de méthode
from flask import Flask
from app.config import configuration


# Dans la variable app on va créer une instance d'application et on lui fournit le nom de notre module en cour 
# Cela va permettre à l'application de trouver les ressources dont elle à besoin dans le dossier en cours
# L'instance d'application est le registre central pour les éléments tel que les vues, les itinéraires d'URL, ou les configuration des modèle
# En somme on initialise l'application Flask
app = Flask(__name__)

# Prise en charge des requêtes
from app.views import controllers

app.register_blueprint(controllers)

app/views.py
# coding: utf8
from flask import render_template, request, Blueprint, redirect, url_for, send_from_directory, current_app
import datetime
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from joblib import load
import calendar




# C'est ici qu'on demande à notre appli flask d'acheminer toutes les demandes d'URL à la racine vers la fonction index()
# A chaque fois qu'on ouvrira un navigateur pour accéder à l'indexe, c'est cette fonction qui sera appelé
# @app.route est un décorateur de la varibale app qui va encapsuler la fonction index() et acheminer les demande vers cette fonction


zoneA = [
    '03', '15', '43', '63', '07', '26', '38', '73', '74', '01', '42', '69', '25', '39', '70', '90', '21',
    '58', '71', '89', '24', '33', '40', '47', '64', '19', '23', '87', '16', '17', '79', '86'
]

zoneB = [
    '22', '29', '35', '56', '18', '28', '36', '37', '41', '45', '54', '55', '57', '88', '08', '10', '51', '52', '67', '68', '02', '60',
    '80', '59', '62', '14', '50', '61', '27', '76', '975', '44', '49', '53', '72', '85', '04', '05', '13', '84', '06', '83'
]

zoneC = ['77', '93', '94', '75', '78', '91', '92', '95', '11', '30',
         '34', '48', '66', '09', '12', '31', '32', '46', '65', '81', '82']

zoneAUTRE = ['2A', '2B', '971', '977', '978',
             '972', '974', '976', '986', '987', '988', '973']

controllers = Blueprint("main", __name__, url_prefix="/")


@controllers.route('/')
def index():

    return render_template('index.html')


@controllers.route('/dashboard')
def dashboard():

    return render_template('dashboard.html')


@controllers.route('/accueil')
def accueil():

    return render_template('index.html')


@controllers.route('/formulaire_predict')
def formulaire_predict():

    return render_template('formulaire_predict.html')


@controllers.route('/predict', methods=['POST', 'GET'])
def predict():

    dep = request.form['dep']
    agg = int(request.form['agg'])
    atm = int(request.form['atm'])
    lum = int(request.form['lum'])
    date_request = request.form['date']
    cat_time = int(request.form['cat_time'])
 
    vacances = int(request.form['vacances'])

  

    # convertir le type de date
    #date = datetime.date(int(date_request[0]), int(date_request[1]), int(date_request[2]))
    date = datetime.date(int(date_request[0:4]), int(
        date_request[5:7]), int(date_request[8:]))
    journee = calendar.day_name[date.weekday()]

    print(date)

    model = load('app/static/visa.joblib')

    prediction = model.predict(
        [[dep, lum, agg, atm, date, cat_time, journee, vacances]])[0]
    #print(prediction)
    dic_prediction = {1: "Faible", 2: "Moyen", 3: "Élevé" }
    str_prediction = dic_prediction[prediction]

    return render_template('predict.html', prediction=prediction, str_prediction=str_prediction, dep=dep, lum=lum, agg=agg, atm=atm, date=date,cat_time=cat_time, journee=journee)


@controllers.route('/offline')
def offline():
    return render_template("offline.html")


@controllers.route('/sw.js')
def sw():
    return send_from_directory(current_app.static_folder, "generate-sw.js")

app/templates/base.html
<!doctype html>
<html lang="fr">

<head>
	<meta charset="UTF-8">
	<title>Sécurité routière</title>
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link rel="stylesheet" href="{{url_for('static', filename='bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{url_for('static', filename='bootstrap.css')}}">
	<link rel="stylesheet" type="text/css" href="/static/style.css" />
	<link rel="manifest" href="{{ url_for('static', filename='manifest.webmanifest') }}">
	<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>   
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

 
</head>

<body>
	<div id="case">
		<header>
			<nav>
				<img src="{{url_for('static', filename='img/NgaMa.png')}}"  width = "100" height = "100" alt="description de l'image" >
				<p class='titre'></p> 
				<a class= 'bouton' href="{{url_for('main.accueil')}}">Accueil    </a>	
				<meta name="viewport" content="width=device-width,initial-scale=1">
	   		    <a class= 'bouton' href="{{ url_for('main.formulaire_predict')}}">  Estimation des risques</a><br>
				<a class= 'bouton' href="{{ url_for('main.dashboard')}}">À propos</a>
			</nav>
			
		</header>
			<section>
                {% block section %}

                {% endblock  %}
			</section>
	  
		<footer> 
			<div class="pied">
				Tous droits réservés © 2021
			</div>
		</footer> 
	</div>
	
	<script type="text/javascript">
		if('serviceWorker' in navigator) {
		navigator.serviceWorker.register("/sw.js");
		};
		
    </script>
	
	
</html>

app/templates/dashboard.html
{% extends 'base.html' %}
{% block title %}accueil{% endblock %}
{% block section %}
			
<section>
    <div class="card" style="width: 100%;">
        <div class="row justify-content-center">
			<div class="col-md-8">
                <br>
        <img class="card-img-top" src="{{url_for('static', filename='img/pompier.jpg')}}" alt="Card image cap">

        <p class="card-text"><h3><strong>Notre entreprise est basée à Cannes-Mandelieu près de l'aeroport .
            Notre équipe est composée de 17 personnes et aide au mieux
            les équipes de secours pour s'organiser lors des accidents .</strong></h3></p>

        <img class="card-img-top" src="{{url_for('static', filename='img/secour_routiere.jpg')}}" alt="Card image cap">
        <div class="card-body">
         
        </div>
            </div>
        </div>
    </div>
    <div id="accordion">
        <div class="card-header" id="headingOne">
            <h4 class="mb-0 ">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    <h5>Notre équipe </h5>
                </button>
            </h4>
        </div>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="row justify-content-center">
                <div class="card-deck">
                    <div class="col-2"></div>
                    <div class="card col-4 text-center">
                        <img class="card-img-top rounded mx-auto d-block" style="width: 50%" src="{{url_for('static', filename='img/marie.jpeg')}}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title text-info font-weight-bold">Marie SCHUTZ</h5>
                            <h6 class="card-title">Développeuse IA et Data</h6>
                            <p class="card-text">Titulaire d'un titre de développeuse web et web mobile, je recherche un contrat en alternance en IA.
                               
                            </p>
                        </div>
                       
                    </div>
                    <div class="card col-4 text-center">
                        <img class="card-img-top rounded mx-auto d-block" style="width: 50%" src="{{url_for('static', filename='img/nga.jpeg')}}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title text-info font-weight-bold">Nga TRAN</h5>
                            <h6 class="card-title ">Développeuse IA et Data</h6>
                            <p class="card-text">Passionnée par les jeux de données et leur modélisation, capable d’adaptation, d’autodidacte et douée d’esprit d’équipe tout en étant autonome, je souhaite développer mes compétences, en les mettant à votre service en intégrant votre entreprise. </p>
                        </div>
                        
                    </div>
                    <div class="col-2"></div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingTwo">
                <h5 class="mb-0">
                    <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        <h5>Algorithme choisi</h5>
                    </button>
                </h5>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                <div class="card-body text-secondary mb-2">
                    <h6>
                       La régression logistique, méthode d'apprentissage supervisé qui utilise un algorithme pour comprendre la relation entre les variables.
                    Avec la régression logistique (ou logit) , nous pouvons faire une analyse prédictive, en mesurant la relation entre ce que nous voulons prédire (variable dépendante) et une ou plusieurs variables indépendantes, c'est-à-dire les caractéristiques.
                    </h6>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingThree">
                <h5 class="mb-0">
                    <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        <h5>Jeux de données travaillées </h5>
                    </button>
                </h5>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                <div class="card-body text-secondary mb-2">
                    <h5 class="ml-3 mb-3">
                        <p>Le fichier national des accidents corporels de la circulation est une bases de données de 2005 à 
                        2019 constitué de 4 fichiers au format csv par année </p> 
                        <div class="ml-5">
                            <p>Caractéristiques</p>
                            <p>Lieux</p>
                            <p>Véhicules</p>
                            <p>Usagers</p>
                        </div>
                    
                        <p>retraçant l’historique des accident ayant eu lieu en France. 
                            <a href="https://www.data.gouv.fr/fr/datasets/bases-de-donnees-annuelles-des-accidents-corporels-de-la-circulation-routiere-annees-de-2005-a-2019/">Sources... </a> 
                        </p>
                        <p> Nous avons utilisé 2 fichiers qui permettent de répondre aux besoins  </p>
                        <div class="ml-5 mt-3">
                            <p> 
                                <div class="font-weight-bold font-italic mb-2">1. Caractéristiques</div> 
                                décrit les circonstances générales de l’accident 
                            </p>
                            <img class="img-fluid" src="{{url_for('static', filename='img/caracteriques.png')}}" class="rounded mx-auto d-block" alt="donnees de caracteriques">
                            <p>
                                <div class="font-weight-bold font-italic  mb-2 mt-3">2. Usagers </div> 
                                chacun des usagers décrits impliqués dans l’accident 
                            </p>
                            <img class="img-fluid" src="{{url_for('static', filename='img/usagers.png')}}" class="rounded mx-auto d-block" alt="donnees de caracteriques">
                        </div>
                    </h5>
                </div>
            </div>
          </div>
    </div>


   
   
	
</section>
            
{% endblock %}	  

app/templates/formulaire_predict.html
{% extends 'base.html' %}
{% block title %}Formulaire{% endblock %}
{% block section %}

	   
	<section>

		<br>
		<strong>
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<form action="{{url_for('main.predict')}}" method="post">
					<div class="form-group row">
						<label for="dep" class="col-sm-2 col-form-label">Votre Département </label>
						<div class="col-sm-10">
							<select class="form-control" id="departementId" name="dep">
								<option disabled selected value="">Choisissez un département dans la liste</option>
							</select>
						</div>
					</div>
					<div class="form-group row">
						<label for="atm" class="col-sm-2 col-form-label">Luminosité</label>
						<div class="col-sm-10">
						<select required class="custom-select mr-sm-2" id="lum" name="lum">
							<option disabled selected value="">Choisissez un niveau de luminosité</option>
							<option value="1">1 – Plein jour</option>
							<option value="2">2 – Crépuscule ou aube</option>
							<option value="3">3 – Nuit sans éclairage public</option>
							<option value="4">4 – Nuit avec éclairage public non allumé</option>
							<option value="5">5 – Nuit avec éclairage public allumé</option>
							</select>
						</div>
					</div>
					
					<fieldset class="form-group">
						<div class="row">
						<legend class="col-form-label col-sm-2 pt-0">Localisation</legend>
						<div class="col-sm-10">
							<div class="form-check">
							<input class="form-check-input" type="radio" name="agg" id="gridRadios2" value="1"  required>
							<label class="form-check-label" for="agg">
								En agglomération
							</label>
							</div>
							<div class="form-check">
							<input class="form-check-input" type="radio" name="agg" id="gridRadios2" value="2"  required>
							<label class="form-check-label" for="agg">
								Hors agglomération
							</label>
							</div>
						</div>
						</div>
					</fieldset>
					<div class="form-group row">
					<label for="atm" class="col-sm-2 col-form-label">Condition Atmospherique</label>
					<div class="col-sm-10">
						<select required class="custom-select mr-sm-2" id="atm" name="atm">
							<option disabled selected value="">Condition atmospherique...</option>
							<option value="1">1 – Normale</option>
							<option value="2">2 – Pluie légère</option>
							<option value="3">3 – Pluie forte</option>
							<option value="4">4 – Neige - grêle</option>
							<option value="5">5 – Brouillard </option>
							<option value="6">6 – Vent fort - tempête</option>
							<option value="7">7 – Temps éblouissant</option>
							<option value="8">8 – Temps couvert  </option>
							<option value="9">9 – Autre</option>
						</select>
					</div>
					</div>
					<div class="form-group row">
						<label for="date" class="col-sm-2 col-form-label">Date </label>
						<div class="col-sm-10">
						<input type="date" class="form-control" id="date" name="date" placeholder="dd/mm/yyyy"  required>
						</div>
					</div>
					<div class="form-group row">
						<label for="cat_time" class="col-sm-2 col-form-label">Période</label>
						<div class="col-sm-10">
						<select class="custom-select mr-sm-2" id="cat_time" name="cat_time"  required>
							<option disabled selected value="">Choisissez un créneau horaire...</option>
							<option value="1">08:00 - 17:00</option>
							<option value="2">17:00 - 20:00</option>
							<option value="3">20:00 - 00:00</option>
							<option value="4">00:00 - 05:00</option>
							<option value="5">05:00 - 08:00</option>
							</select>
						</div>
					</div>


					<div class="form-group row">
						<label for="vacances" class="col-sm-2 col-form-label">Vacances</label>
						<div class="col-sm-10">
							<select required class="custom-select mr-sm-2" id="vacances" name="vacances">
								<option disabled selected value="">Période de vacances</option>
								<option value="0">Non</option>
								<option value="1">jour ferié,ect...</option>
								<option value="2">Oui</option>
								
							</select>
						</div>
						</div>
						<div class="form-group row">
							<div class="col-sm-10">
								<button type="submit" class="btn btn-primary">Predire</button>
							</div>
							</div>

						
				</form>
			</div>
		</div>
	</div>
</strong>
</section>

<script>
	$.getJSON('static/donnees/departments_FR.json', function(departments){
		if (departments === undefined || departments.length === 0) 
			return
		var select = document.getElementById("departementId");
	
		for(let dpt of departments) {
			var option = document.createElement("option");
			option.value = dpt.departmentCode;
			option.innerHTML = dpt.departmentCode + " - " + dpt.departmentName  ;
			select.appendChild(option);
		}
	});
</script>

{% endblock %}
	

app/templates/index.html
{% extends 'base.html' %}
{% block title %}accueil{% endblock %}
{% block section %}

<section>
	
<div style class='truc'>

	<div style class='machin'>
			<img class='yy' src="{{url_for('static', filename='img/fond.jpeg')}}"  width = "100%"> 
	</div>

		<div style class='bidule'>
			
			<p class="din">	
		Nous sommes là pour vous aider à prévoir le risque d'accident et ainsi pouvoir mobiliser les services de secours
		necessaire pour un jour donné nous avons séparé les prédictions des risques 
		en 3 niveaux.
		<br>
		Cliquez sur le lien estimation <br>des risques pour obtenir<br>
		 une prévision des risques en<br> fonction d'un Jour donné.
			</p> 
		<div>
		   <p class="dingue">	
		<br>
		1 – Faible  
		<br>
		2 – Moyen 
		<br> 
		3 – Élevé  
		</p>
		   
		
</div>
	</section>

{% endblock %}	  
		

app/templates/offline.html
<p><h3>Ceci est une page d'erreur vous devriez changer de page</h3></p>

app/templates/predict.html
{% extends 'base.html' %}
{% block title %}Resultat{% endblock %}
{% block section %}

<section>
	<form class="resultat">
		<div class="row mb-3">		
			<legend><h3>RÉSULTAT</h3></legend>
		</div>
		<div class="container-fluid justify-content-center row">
			<div class="col-lg-6 col-12 bg-light">
				<div class="row p-2 ml-2 text-info">
					<div class="col-md-4 col-sm-12 font-weight-bold">
						Département
					</div>
					<div class="col-md-8 col-sm-12 "> 
						{{dep}}
					</div>
				</div>
				<div class="row p-2 ml-2 text-info">
					<div class="col-md-4 col-sm-12 font-weight-bold ">
						Luminosité 
					</div>
					<div class="col-md-8 col-sm-12">
						{% if lum==1 %} Plein jour 
						{%elif lum==2 %} Crépuscule ou aube
						{%elif lum==3 %} Nuit sans éclairage public
						{%elif lum==4 %} Nuit avec éclairage public non allumé
						{%else %} Nuit avec éclairage public allumé 
						{%endif %}
					</div>
				</div>
				<div class="row p-2 ml-2 text-info">
					<div class="col-md-4 col-sm-12 font-weight-bold ">
						Localisation 
					</div>
					<div class="col-md-8 col-sm-12">
						{% if lum==1 %} En agglométation {%else %} Hors agglométation {%endif %}
					</div>
				</div>
				<div class="row p-2 ml-2 text-info">
					<div class="col-md-4 col-sm-12 font-weight-bold ">
						Atmosphère 
					</div>
					<div class="col-md-8 col-sm-12">
						{% if atm==1 %} Normale 
						{%elif atm==2 %} Pluie légère
						{%elif atm==3 %} Pluie forte
						{%elif atm==4 %} Neige - grêle
						{%elif atm==5 %} Brouillard 
						{%elif atm==6 %} Vent fort - tempête
						{%elif atm==7 %} Temps éblouissant
						{%elif atm==8 %} Temps couvert 
						{%else %} Autre 
						{%endif %}
					</div>
				</div>
				<div class="row p-2 ml-2 text-info">
					<div class="col-md-4 col-sm-12 font-weight-bold ">
						Date 
					</div>
					<div class="col-md-8 col-sm-12">
						{{ journee }} - {{ date }}
					</div>
				</div>
				<div class="row p-2 ml-2 text-info"> 
					<div class="col-md-4 col-sm-12 font-weight-bold ">
						Moment 
					</div>
					<div class="col-md-8 col-sm-12 ">
						{% if cat_time==1 %} 08:00 - 17:00 
						{%elif cat_time==2 %} 17:00 - 20:00
						{%elif cat_time==3 %} 20:00 - 00:00
						{%elif cat_time==4 %} 00:00 - 05:00
						{%else %} 05:00 - 08:00 
						{%endif %}
					</div>
				</div>
			</div>
		<div class="col-lg-6 col-12">
			<fieldset>
				<h3 class="mt-5">
					Tendance du jour :  {{ prediction }} 
				</h3>
				<h4 class="font-weight-bold p-3 text-center shadow-none mb-5 bg-light rounded">
					{% if prediction==1 %}
						<div class="text-secondary">Le niveau de Tendance est {{str_prediction}}</div>
					{% elif prediction==2 %}
						<div class="text-warning">Le niveau de Tendance est {{str_prediction}}</div>
					{% else %}
						<div class="text-danger">Le niveau de Tendance est {{str_prediction}}</div>
					{% endif %}
				</h4>
			</fieldset>
		</div>
		<div class="row">		
			<img class="img-fluid rounded mx-auto d-block" src="{{url_for('static', filename='img/nvsecour.jpeg')}}" alt="Image secours">
		</div>
	</form>
	
</section>

{% endblock %}